# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules
import os
pathex=[os.path.abspath('.')]

a = Analysis(
    ['lims.py'],
    pathex,
    binaries=[],
    datas=[
    ('updater.exe', '.'),
    ('odbc_driver_install.exe', '.'),
    ('lims/config/*.py', 'lims/'),
    ('lims/core/*.py', 'core/'),
    ('lims/reports/*.py', 'reports/'),
    ('lims/packages/*.py', 'packages/'),
    ('lims/resources_rc.py', 'lims/'),
    ('lims/dependencies/fonts/*.ttf', 'dependencies/fonts/'),
    *collect_data_files('openpyxl'), # ✅ Explicitly include packages
],
    hiddenimports=[
    'fitz',
    'pyodbc',
    'sip',
    'bcrypt',
    *collect_submodules('PyQt5'),
    *collect_submodules('openpyxl'),
    'config.config',
    'config.file_paths',
    'config.lab_lists',
    'config.methods_tables',
    'config.patterns',
    'config.tables',
    'core.AlphaSpec',
    'core.CalibrationCertificate',
    'core.Fluorescence',
    'core.GAB',
    'core.GammaSpec',
    'core.ICPMS',
    'core.LSC',
    'core.Version',
    'core.WetChem',
    'core.consumable_form',
    'core.get_data',
    'packages.Analyte',
    'packages.BatchID',
    'packages.DQO',
    'packages.Prepsheet',
    'packages.ResultType',
    'packages.patterns',
    'packages.report_setup',
    'reports.data_package',
    'reports.edd',
    'reports.form_1',
    'reports.pdr',
],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['set_excepthook.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='lims',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['lims\\images\\leidos_logo.ico'],
)