method_list = ["CVAAS",
                "ISOAm",
                "ISOTh",
                "ISOU",
                "ISOPu",
                "GammaSpec",
                "GAB",
                "LSCPu",
                "LSCRa",
                "LSCTotal",
                "ICPMS (Soil)",
                "ICPMS (Aqueous)",
                "ICPMS (Smear)",
                "ICPMS (Air Filter)",
                "Fluorescence",
                "XRD",
                "TSP",
                "Fluoride",
                "Ammonia",
                "Nitrates",
                "Nitrites",
                "Cyanide",
                "Chloride",
                "pH",
                "TSS"]

consumable_type_list = ['Reagent', 
                        'Tracer', 
                        'Standard', 
                        'LCS', 
                        'Equipment Consumable']

prepsheet_columns = {
    "CVAAS": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "ISOAm": ['Sample ID', 'Aliquot (mL)', "Am-243\n(g)", 'Analysis Date', 'Analysis Time', 'Analyst',  "Alpha\nChamber"],
    "ISOTh": ['Sample ID', 'Aliquot (mL)', "Th-229\n(g)", 'Analysis Date', 'Analysis Time', 'Analyst', "Alpha\nChamber"],
    "ISOU": ['Sample ID', 'Aliquot (mL)', "U-232\n(g)", 'Analysis Date', 'Analysis Time', 'Analyst',  "Alpha\nChamber"],
    "ISOPu": ['Sample ID', 'Aliquot (mL)', "Pu-238\n(g)", 'Analysis Date', 'Analysis Time', 'Analyst', "Alpha\nChamber", "Tracer\nRecovery\n(%)"],
    "GammaSpec": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst', "APEX\nSample ID", "Gamma\nDET"],
    "GAB": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst', "Carrier ID"],
    "LSCPu": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "LSCRa": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "LSCTotal": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "ICPMS (Air Filter)": ['Sample ID', 'Aliquot (g)', "Filtered (y/n)", 'Analysis Date', 'Analysis Time', 'Analyst'],
    "ICPMS (Aqueous)": ['Sample ID', 'Aliquot (g)', "Filtered (y/n)", 'Analysis Date', 'Analysis Time', 'Analyst'],
    "ICPMS (Smear)": ['Sample ID', 'Aliquot (g)', "Filtered (y/n)", 'Analysis Date', 'Analysis Time', 'Analyst'],
    "ICPMS (Soil)": ['Sample ID', 'Aliquot (g)', "Filtered (y/n)", 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Fluorescence": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "XRD": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "TSP": ['Sample ID', 'Aliquot (mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Fluoride": ['Sample ID', 'Aliquot (mL)', 'Fluoride Result (mg/mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Ammonia": ['Sample ID', 'Aliquot (mL)', 'Ammonia Result (mg/mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Nitrates": ['Sample ID', 'Aliquot (mL)', 'Nitrates Result (mg/mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Nitrites": ['Sample ID', 'Aliquot (mL)', 'Nitrites Result (mg/mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Cyanide": ['Sample ID', 'Aliquot (mL)', 'Cyanide Result (mg/mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "Chloride": ['Sample ID', 'Aliquot (mL)', 'Chloride Result (mg/mL)', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "pH": ['Sample ID', 'Aliquot (mL)', 'Sample\nTemp (°C)', 'pH Result', 'Analysis Date', 'Analysis Time', 'Analyst'],
    "TSS": ['Sample ID', 'Aliquot (mL)', "Initial\nMass\n(g)", "Intermediate\nMass\n(g)", "Final\nMass\n(g)", "Total\nSolid\n(mg)", "TSS Result\n(mg/mL)", 'Analysis Date', 'Analysis Time', 'Analyst']
}

methods_qc = {"CVAAS": ['BLK', 'LCS', 'DUP'],
                "ISOAm": ['BLK', 'LCS', 'DUP'],
                "ISOTh": ['BLK', 'LCS', 'DUP'],
                "ISOU": ['BLK', 'LCS', 'DUP'],
                "ISOPu": ['BLK', 'LCS', 'DUP'],
                "GammaSpec": ['BLK', 'LCS', 'DUP'],
                "GAB": ['BLK', 'LCSA', 'LCSB', 'DUP'],
                "LSCPu": ['BLK', 'LCS', 'DUP'],
                "LSCRa": ['BLK', 'LCS', 'DUP'],
                "LSCTotal": ['BLK', 'LCS', 'DUP'],
                "ICPMS (Air Filter)": ['BLK', 'LCS', 'LCSDUP'],
                "ICPMS (Aqueous)": ['BLK', 'LCS', 'MS', 'MSDUP'],
                "ICPMS (Smear)": ['BLK', 'LCS', 'LCSDUP'],
                "ICPMS (Soil)": ['BLK', 'LCS', 'DUP', 'MS'],
                "Fluorescence": ['BLK', 'LCS', 'DUP'],
                "XRD": ['BLK', 'LCS', 'DUP'],
                "TSP": ['BLK', 'LCS', 'DUP'],
                "Fluoride": ['BLK', 'LCS', 'DUP'],
                "Ammonia": ['BLK', 'LCS1', 'LCS2', 'DUP'],
                "Nitrates": ['BLK', 'LCS', 'DUP'],
                "Nitrites": ['BLK', 'LCS', 'DUP'],
                "Cyanide": ['BLK', 'LCS', 'DUP'],
                "Chloride": ['BLK', 'LCS', 'DUP'],
                "pH": ['BLK', 'LCS', 'DUP'],
                "TSS": ['BLK', 'LCS', 'DUP']}

