method_list = ["CVAAS",
                "ISO-Am",
                "ISO-Th",
                "ISO-U",
                "ISO-Pu",
                "GammaSpec",
                "GAB",
                "LSC-Pu",
                "LSC-Ra",
                "LSC-Total",
                "ICPMS (Soil)",
                "ICPMS (Aqueous)",
                "ICPMS (Smear)",
                "ICPMS (Air Filter)",
                "Fluorescence",
                "XRD",
                "TSP",
                "Fluoride",
                "Ammonia",
                "Nitrates",
                "Nitrites",
                "Cyanide",
                "Chloride",
                "pH",
                "TSS"]

consumable_type_list = ['Reagent', 
                        'Tracer', 
                        'Standard', 
                        'LCS', 
                        'Equipment Consumable']

prepsheet_columns = {
    "pH": ["Sample ID", "Aliquot\n(mL)", "Sample\nTemp.\n(°C)", "pH Result", "Sample Date", "Sample Time", "Analyst"],
    "GAB": ["Sample ID", "Aliquot\n(mL)", "Sample Date", "Sample Time", "Analyst", "Carrier ID"],
    "Gamma": ["Sample ID", "Aliquot\n(mL)", "Sample Date", "Sample Time", "Analyst", "APEX\nSample ID", "Gamma\nDET"],
    "ICPMS (Air Filter)": ["Sample ID", "Aliquot\n(g)", "Filtered?", "Sample Date", "Sample Time", "Analyst"],
    "ICPMS (Aqueous)": ["Sample ID", "Aliquot\n(g)", "Filtered?", "Sample Date", "Sample Time", "Analyst"],
    "ICPMS (Smear)": ["Sample ID", "Aliquot\n(g)", "Filtered?", "Sample Date", "Sample Time", "Analyst"],
    "ICPMS (Soil)": ["Sample ID", "Aliquot\n(g)", "Filtered?", "Sample Date", "Sample Time", "Analyst"],
    "ISOTh": ["Sample ID", "Aliquot\n(mL)", "Th-229\n(g)","Sample Date", "Sample Time", "Analyst", "Alpha\nChamber"],
    "ISOPu": ["Sample ID", "Aliquot\n(mL)", "Pu-238\n(g)", "Sample Date", "Sample Time", "Analyst", "Alpha\nChamber", "Tracer\nRecovery\n(%)"],
    "ISOU": ["Sample ID", "Aliquot\n(mL)", "U-232\n(g)", "Sample Date", "Sample Time", "Analyst", "Alpha\nChamber"],
    "ISOAm": ["Sample ID", "Aliquot\n(mL)", "Am-243\n(g)", "Sample Date", "Sample Time", "Analyst", "Alpha\nChamber"],
    "TSS": ["Sample ID", "Aliquot\n(L)", "Initial\nMass\n(g)", "Intermediate\nMass\n(g)", "Final\nMass\n(g)", "Total\nSolid\n(mg)", "TSS Result\n(mg/L)", "Sample Date", "Sample Time", "Analyst"],
    "Ammonia": ["Sample ID", "Aliquot\n(mL)", "Ammonia\nResult\n(mg/L)", "Sample Date", "Sample Time", "Analyst"],
    "Fluoride": ["Sample ID", "Aliquot\n(mL)", "Fluoride\nResult\n(mg/L)", "Sample Date", "Sample Time", "Analyst"],
    "Fluorescence": ["Sample ID", "Sample Date", "Sample Time", "Analyst"]
}
