from lims.config.tables import AlphaSpecResults, GammaSpecResults, GABResults, ICPMSResults, FluorescenceResults, LSCResults, WetChemResults

methods_tables = {#"FIMS": FIMSResults,
                "ISOAm": AlphaSpecResults,
                "ISOTh": AlphaSpecResults,
                "ISOU": AlphaSpecResults,
                "ISOPu": AlphaSpecResults,
                "GammaSpec": GammaSpecResults,
                "GAB": GABResults,
                "LSCPu": LSCResults,
                "LSCRa": LSCResults,
                "LSCTotal": LSCResults,
                "ICPMS (Soil)": ICPMSResults,
                "ICPMS (Aqueous)": ICPMSResults,
                "ICPMS (Smear)": ICPMSResults,
                "ICPMS (Air Filter)": ICPMSResults,
                #'TCLP': TCLPResults,
                "Fluorescence": FluorescenceResults,
                #"XRD": XRDResults,
                #"TSP": TSPResults,
                "Fluoride": WetChemResults,
                "Ammonia": WetChemResults,
                "Nitrates": WetChemResults,
                "Nitrites": WetChemResults,
                "Cyanide": WetChemResults,
                "Chloride": WetChemResults,
                "pH": WetChemResults,
                "TSS": WetChemResults}
