from lims.config.tables import AlphaSpecResults, GAMMAResults, GFPCResults, MetalsResults, FluorescenceResults, LSCResults, WetChemResults

methods_tables = {#"FIMS": FIMSResults,
                "ISOAm": AlphaSpecResults,
                "ISOTh": AlphaSpecResults,
                "ISOU": AlphaSpecResults,
                "ISOPu": AlphaSpecResults,
                "GAMMA": GAMMAResults,
                "GFPC": GFPCResults,
                "LSCPu": LSCResults,
                "LSCRa": LSCResults,
                "LSCTotal": LSCResults,
                "Metals": MetalsResults,
                #'TCLP': TCLPResults,
                "Fluorescence": FluorescenceResults,
                #"XRD": XRDResults,
                #"TSP": TSPResults,
                "Fluoride": WetChemResults,
                "Ammonia": WetChemResults,
                "Nitrates": WetChemResults,
                "Nitrites": WetChemResults,
                "Cyanide": WetChemResults,
                "Chloride": WetChemResults,
                "pH": WetChemResults,
                "TSS": WetChemResults}
