from lims.config.tables import ALPHAResults, GAMMAResults, GFPCResults, METResults, BEFResults, LSCResults, WetChemResults, HGResults

methods_tables = {"HG": HGResults,
                "ISOAM": ALPHAResults,
                "ISOTH": ALPHAResults,
                "ISOU": ALPHAResults,
                "ISOPU": ALPHAResults,
                "GAMMA": GAMMAResults,
                "GFPC": GFPCResults,
                "LSCPU": LSCResults,
                "LSCSR": LSCResults,
                "LSCAB": LSCResults,
                "MET": METResults,
                'TCLP': METResults,
                #'TCLP': TCLPResults,
                "BEF": BEFResults,
                #"SIO2": XRDResults,
                #"TSP": TSPResults,
                'FLUOR': WetChemResults,
                "NH3": WetChemResults,
                "NO3": WetChemResults,
                "NO2": WetChemResults,
                "CRVI": WetChemResults,
                "CL": WetChemResults,
                "PH": WetChemResults,
                "TSS": WetChemResults}
